version: '3.2'
services:
  zero:
    image: dgraph/dgraph:latest
    container_name: mappslab-dev_dgraph-zero
    volumes:
      - type: volume
        source: dgraph-mappslab
        target: /dgraph-mappslab
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  server:
    container_name: mappslab-dev_dgraph-server
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph-mappslab
        target: /dgraph-mappslab
        volume:
          nocopy: true
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=server:7080 --lru_mb=2048 --zero=zero:5080
  ratel:
    container_name: mappslab-dev_dgraph-ratel
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph-mappslab
        target: /dgraph-mappslab
        volume:
          nocopy: true
    ports:
      - 8090:8000
    command: dgraph-ratel
  localstack:
    image: localstack/localstack:latest
    container_name: mappslab-dev_localstack
    ports:
      - '4563-4584:4563-4584'
      - '8050:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  dgraph-mappslab:
