version: '3.2'
services:
  zero:
    image: dgraph/dgraph:latest
    container_name: mappslab-test_dgraph-zero
    volumes:
      - type: volume
        source: dgraph-mappslab
        target: /dgraph-mappslab
        volume:
          nocopy: true
    ports:
      - 5081:5080
      - 6081:6080
    restart: on-failure
    command: dgraph zero --port_offset 1 --my=zero:5081
  server:
    container_name: mappslab-test_dgraph-server
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph-mappslab
        target: /dgraph-mappslab
        volume:
          nocopy: true
    ports:
      - 8081:8080
      - 9081:9080
    restart: on-failure
    command: dgraph alpha --my=server:7081 --lru_mb=2048 --zero=zero:5081
  ratel:
    container_name: mappslab-test_dgraph-ratel
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph-mappslab
        target: /dgraph-mappslab
        volume:
          nocopy: true
    ports:
      - 8091:8000
    command: dgraph-ratel

  localstack:
    image: localstack/localstack
    ports:
      - '4567-4584:4567-4584'
      - '${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}'
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - '${TMPDIR:-/tmp/localstack}:/tmp/localstack'

volumes:
  dgraph-mappslab:
